language: node_js
node_js:
- node
dist: trusty
addons:
  apt:
    packages:
      - libnss3
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- "sysctl kernel.unprivileged_userns_clone=1"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
install:
- npm install
script:
- npm run test
- npm run dev_build